MUSIC_GENERATOR:
  DEFAULT_DURATION: 180
  DEFAULT_FORMAT: "mp3"
  DEFAULT_FILENAME: "background_music"
  OUTPUT_DIR: "workflow/outputs/music"
  POLLING_INTERVAL: 5
  REQUEST_TIMEOUT: 30
  DOWNLOAD_TIMEOUT: 60